name: energychat
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  avatar_glow: ^2.0.2
  chat_gpt_sdk: ^2.2.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  speech_to_text: ^6.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/sounds/speech_to_text_listening.m4r
    # - assets/sounds/speech_to_text_cancel.m4r
    # - assets/sounds/speech_to_text_stop.m4r
