name: energychat
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  avatar_glow: ^2.0.2
  chat_gpt_sdk: ^2.2.5
  dio: ^5.3.4
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_ui_auth: ^1.10.0
  firebase_ui_oauth_google: ^1.2.14
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  speech_to_text: ^6.4.1
  syncfusion_flutter_pdfviewer: ^23.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/sounds/speech_to_text_listening.m4r
    # - assets/sounds/speech_to_text_cancel.m4r
    # - assets/sounds/speech_to_text_stop.m4r
