// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpOEIV5HgQUT0uCg8_tnxDH8lyI8kqdI',
    appId: '1:52198056977:web:1072804db3c76083ef3db0',
    messagingSenderId: '52198056977',
    projectId: 'silken-order-386923',
    authDomain: 'silken-order-386923.firebaseapp.com',
    storageBucket: 'silken-order-386923.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKzb5xQEYwnL0a9nrPupz7mY3t1oanRk',
    appId: '1:52198056977:android:27ef1892c0401982ef3db0',
    messagingSenderId: '52198056977',
    projectId: 'silken-order-386923',
    storageBucket: 'silken-order-386923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjX4rlKQXiCEk4KxTdMTwR4SQfeiYDEc',
    appId: '1:52198056977:ios:9d5d953bdaf5d69fef3db0',
    messagingSenderId: '52198056977',
    projectId: 'silken-order-386923',
    storageBucket: 'silken-order-386923.appspot.com',
    iosBundleId: 'com.example.energychat',
  );
}
